version: '3'

services:
  node-app:
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: postgres://pafin_user:pafin_password@postgres:5432/pafin_db
      JWT_SECRET: abcehdfgfdf
    ports:
      - "3005:3000"
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - /app/node_modules

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: pafin_db
      POSTGRES_USER: pafin_user
      POSTGRES_PASSWORD: pafin_password
    ports:
      - "54322:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./volumes/db:/var/lib/postgresql/data
volumes:
  postgres-data:
  node-modules: